[project]
name = "video-annotation-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imutils>=0.5.4",
    "opencv-contrib-python>=4.12.0.88",
]
